// Generated by CoffeeScript 1.4.0
var ssh;

module["export"] = ssh = function(command, callback, exitCallback) {
  var args, child, mask, options, stars, user;
  if (!command) {
    throw new Error(this.address + ": No command to run");
  }
  user = this.user;
  options = this.sshOptions;
  mask = this.logMask;
  stars = void 0;
  args = ["-l" + user, this.address, "''" + command + "''"];
  child = void 0;
  if (options) {
    args = options.concat(args);
  }
  if (mask) {
    stars = star(mask);
    while (command.indexOf(mask) !== -1) {
      command = command.replace(mask, stars);
    }
  }
  this.log(user + ":ssh: " + command);
  child = spawn("ssh", args);
  return this.listen(child, callback, exitCallback);
};
