// Generated by CoffeeScript 1.4.0
var Logger, Ssh, Ssh2;

Ssh2 = require('ssh2');

Logger = require('./logger');

module.exports = Ssh = (function() {

  function Ssh(o, cb) {
    var _this = this;
    if (!(this.host = o.host)) {
      return cb('host is required');
    }
    if (!(this.pass = o.pass)) {
      return cb('pass is required');
    }
    if (!(this.cmd = o.cmd)) {
      return cb('cmd is required');
    }
    this.user = o.user || 'root';
    this.port = o.port || 22;
    this.ssh = new Ssh2();
    Logger.out('connecting');
    this.ssh.on('connect', function() {
      return Logger.out('connected');
    });
    this.ssh.on('ready', function() {
      Logger.out('ready');
      return _this.ssh.exec(_this.cmd, function(err, stream) {
        if (err) {
          return cb(err);
        }
        stream.on('data', function(data, extended) {
          Logger.out("" + (extended === 'stderr' ? 'stderr' : 'stdout') + ": " + data);
          if (o.stream_data) {
            return o.stream_data.apply(null, arguments);
          }
        });
        stream.on('end', function() {
          Logger.out('stream EOF');
          if (o.stream_end) {
            return o.stream_end;
          }
        });
        stream.on('close', function() {
          Logger.out('stream closed');
          if (o.stream_close) {
            return o.stream_close;
          }
        });
        return stream.on('exit', function(code, signal) {
          Logger.out("stream exit code " + code + ", signal " + signal);
          if (o.stream_exit) {
            o.stream_exit.apply(null, arguments);
          }
          _this.ssh.end();
          return cb(null);
        });
      });
    });
    this.ssh.on('error', function(err) {
      Logger.out("Connection error: " + err);
      if (o.error) {
        return o.error.apply(null, arguments);
      }
    });
    this.ssh.on('end', function() {
      Logger.out("Connection end");
      if (o.end) {
        return o.end;
      }
    });
    this.ssh.on('close', function() {
      Logger.out("Connection closed");
      if (o.close) {
        return o.close;
      }
    });
    this.ssh.connect({
      host: this.host,
      port: this.port,
      username: this.user,
      password: this.pass
    });
  }

  return Ssh;

})();
